config/routes.rb
Rails.application.routes.draw do
  # resources :question
  resources :option
  resources :answer

  get 'question/add_question'
  get 'question/add_question'
  post 'question/save_question'
  delete 'question/delete/:id', to: 'question#delete'

  get 'survey/index'
  get 'survey/', to: 'survey#index'
  get 'survey/edit'
  get 'survey/add_survey'
  get 'survey/show'
  get 'survey/show/:id', to: 'survey#show'
  get 'survey/delete'
  get 'survey/answers'
  get 'survey/answer_details'
  delete 'survey/delete/:id', to: 'survey#delete'
  post 'survey/save_survey'
  post 'survey/publish', to: 'survey#publish'


  get 'online-survey', to: 'answer#show'
  post 'online-survey', to: 'answer#create'




  devise_for :user
  post '/user', to: 'user#show'
  root 'home#index'
  #
  resources :user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  before_action :authenticate_user!
  def add_question
    @survey_id = params[:survey_id]
    @authenticity_token = params[:authenticity_token]
    @question = SurveyQuestion.new
  end

  def save_question
    @question = SurveyQuestion.new(question_params)

    if @question.save
      if params[:type] != 1 && !params[:options].blank?
        @options = params[:options]
        @question_id = @question.id
        OptionController.saveOptions(@options, @question_id)
      end
      redirect_to :controller => 'survey', :action => 'show', :id => @question.survey_id
    else
      render 'add_question'
    end
  end

  def delete
    @question = SurveyQuestion.find(params[:id])
      if @question.delete
        @options = QuestionOption.where(:survey_question_id => params[:id])
        for option in @options
          option.delete
        end
        redirect_to  :controller => 'survey', :action => 'show', id: params[:survey_id]
      end
  end

  private
  def question_params
    params.require(:survey_question).permit(:survey_id, :question_text, :question_type)
  end


end

app/helpers/question_helper.rb
module QuestionHelper

  def question_error_messages!
    return "" if @question.errors.empty?

    messages = @question.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: @question.errors.count,
                      resource: @question.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/views/question/_form.html.erb
<div class="optionForm">
  <%= label_tag "Option Text" %>
  <br>
  <%= text_field_tag "options[]" %> <a href="#" onclick="removeOption($(this))" class="remove-option" > X </a>
  <br>
</div>

app/views/question/add_question.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <%= form_for(@question, url: question_save_question_path) do |f| %>
        <%= question_error_messages! %>

    <div class="modal-header">
      <h4 class="modal-title">Add Question</h4>
    </div>
    <div class="modal-body">

      <%= f.label :Question_Text %>
      <%= f.text_area :question_text %>

      <%= f.label :Question_Type %>


      <%= f.select(:question_type) do %>
          <% [
                 ['__select type__', ''],
                 ['Comment/Essay Box', 'textarea'],
                 ['Multiple Choice (Only One Answer)', 'radio'],
                 ['Multiple Choice (Multiple Answers)', 'checkbox'],
                 ['DropDown list (Only One Answer)', 'dropdown']
             ].each do |c| -%>
              <%= content_tag(:option, c.first, value: c.last) %>
          <% end %>
      <% end %>
      <%= f.hidden_field(:survey_id, {:value => @survey_id}) %>

        <div id="question_options">
        </div>
        <a href="javascript:;" id="addNewOption">Add New Option</a>


      <div class="clearfix"></div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn pull-left" onclick="window.location.href='/survey/show/<%= @survey_id %>'">
          <span class="btn-label-icon left"><i class="fa fa-times"></i></span>Cancel
      </button>
      <button type="submit" class="btn pull-right "><span class="btn-label-icon left"><i class="fa fa-floppy-o"></i></span>Save</button>
    </div>
    <% end %>
  </div>
</div>

<div style="display: none;" id="new_option_form">
  <% @form = "form" %>
  <%= render partial: @form, locals: {option: false} %>
</div>

<script>
    $( document ).ready(function() {
        type = $("#survey_question_question_type").val()
        if (type == 'textarea' || type =='')
          $("#addNewOption").hide();
        else
          $("#addNewOption").show();
    });

    $("#survey_question_question_type").on("change",function() {
        switch($(this).val()){
            case 'radio':
            case 'checkbox':
            case 'dropdown':
                $("#addNewOption").show();
                break;
            default:
                $("#addNewOption").hide();
                $("#question_options").html('');
                break;
        }
    });
    $("#addNewOption").on("click", function() {
        $("#question_options").append($("#new_option_form").html());
    });

    function removeOption(element) {
        return element.parent().remove();
    };
</script>